# Generated by Django 2.0.7 on 2018-07-14 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_to', models.CharField(choices=[('GO', 'Gina Ortiz'), ('RT', 'Rick Tallon'), ('MF', 'Matt Foster')], default='GO', max_length=2, verbose_name='Send mail to')),
                ('subject', models.CharField(max_length=150)),
                ('mail_date', models.DateTimeField(auto_now=True)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40, verbose_name='first name')),
                ('last_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='mail',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myMsgApp.Person'),
        ),
    ]
